export const birthOfTheMoonSections = [
  {
    "label": "Prologue",
    "title": "The Long Fire",
    "paragraphs": [
      "Before there were names, before there were witnesses, there was heat.",
      "Not fire as flame, but fire as condition — pressure without rest, fusion without memory. The Sun burned not as a king upon a throne, but as a furnace without intention, an engine whose only law was continuation. Around it, matter gathered, scattered, gathered again. Nothing was placed. Everything was becoming.",
      "The young solar system was not orderly. It was crowded, loud with motion, thick with debris. Worlds were not yet worlds; they were arguments in progress, masses negotiating gravity through collision and near-miss. Orbits overlapped. Paths wandered. Stability was rare and temporary.",
      "Gravity, even then, was not command. It was relationship.",
      "It did not decree where bodies must go; it whispered where they might remain. It allowed closeness, tolerated distance, punished neither — it simply remembered every motion and answered it in kind.",
      "In that long fire, nothing existed alone.",
      "The Sun did not rule. It anchored.",
      "From its heat came gradients, from gradients came motion, and from motion came the possibility of form. This was not creation by will, but creation by consequence. A universe learning, through repetition, what could last.",
      "Earth was not yet Earth as we know her. She was molten, breathing rock and metal, shedding skin as quickly as it formed. She spun too fast. She burned too hot. She had no oceans to soften her surface, no moon to slow her turning. Time had not yet learned to keep pace with her.",
      "And Earth was not alone in her becoming.",
      "Elsewhere in the same band of space, born of the same stellar inheritance, another body took shape. Not an intruder from afar, not a stranger, but kin — shaped by the same fire, bound to the same Sun, moving through the same unstable neighborhood.",
      "The long fire does not choose.",
      "It only prepares.",
      "And from preparation comes meeting."
    ]
  },
  {
    "label": "Movement I",
    "title": "Earth Becoming",
    "paragraphs": [
      "Before the Moon, before the measure of months and the easing of nights, Earth existed alone.",
      "She did not yet know herself as Earth. But mass had begun to notice mass, and motion had begun to remember its own repetition. Something like orientation stirred — not thought, not will, but the difference between staying and drifting. Spin was no longer just spin; it was persistence. Gravity was no longer just pull; it was relation. In that first, wordless awareness, Earth stood where she had been, and did not leave.",
      "She was not yet a world fit for watching.",
      "She spun too fast. Her surface was a skin of fire and fracture, oceans of magma folding over one another, continents unborn and unimagined. The day was short and breathless. The night barely arrived before it fled again. Nothing lingered long enough to remember itself.",
      "Earth was alive, but unbalanced.",
      "Gravity held her together, but only just. The Sun’s pull bound her path, yet offered no instruction. Around her moved debris, siblings-in-waiting, remnants of formation still deciding what they would become. Some rushed inward, volatile and impatient, burning themselves down toward the Sun. Others drifted outward, gathering cold and distance, learning slowness. Earth remained between these extremes, neither consumed nor withdrawn, unsettled but capable of endurance.",
      "The early solar system was crowded, intimate, and unstable — worlds brushing past one another like arguments in progress, each negotiating whether it would stay whole or be scattered.",
      "Earth carried within her the promise of stillness, but not the means.",
      "Her rotation scattered energy outward. Heat refused to settle. Without a companion to temper her motion, she could not cool, could not slow, could not listen to herself long enough to change. Time had not yet learned how to stretch.",
      "This was not failure. It was adolescence.",
      "Earth was becoming, not broken. She needed friction. She needed interruption. She needed a relationship strong enough to survive catastrophe and gentle enough to create rhythm.",
      "Deep within her mantle, currents folded and refolded, rehearsing future continents. Somewhere beneath the violence, the conditions for oceans were being negotiated. Life was possible — but only if the world could learn patience.",
      "And patience does not arise in isolation.",
      "So Earth turned through the dark, radiant and unfinished, carrying more energy than she could hold, moving through a shared sky where another body traced a neighboring path — close enough to matter, distant enough to delay.",
      "The story had not yet reached collision. But the need for it had already begun.",
      "Earth was ready to be changed."
    ]
  },
  {
    "label": "Movement II",
    "title": "Theia, the Companion",
    "paragraphs": [
      "She was not born elsewhere.",
      "Theia rose from the same inheritance as Earth — forged from the same stellar debris, warmed by the same long fire, bound to the same Sun. If Earth was becoming through endurance, Theia was becoming through motion. Where Earth gathered herself inward, Theia carried her mass lightly, her path more wandering, her future less settled.",
      "They were kin long before they were close.",
      "Theia traced an orbit that crossed Earth’s neighborhood again and again, not as an intruder but as a companion world, familiar in composition, different in temperament. She was smaller, but not lesser. Her density, her momentum, her angle through space marked her as a body whose fate would not be stillness.",
      "In later ages, people would search for names to describe such closeness.",
      "They would call it sisterhood, or companionship, or love.",
      "But before language, there was only gravity — the slow recognition between masses that share a history. Earth and Theia felt one another not as desire, but as tension: a pull that could not be ignored and could not be satisfied without change.",
      "Theia carried with her what Earth lacked.",
      "She brought interruption. She brought risk. She carried the excess motion that Earth needed to shed in order to grow. Where Earth was too whole, Theia was willing to be transformed. Where Earth endured, Theia would be spent.",
      "This was not sacrifice by intention.",
      "It was role by consequence.",
      "Theia did not orbit Earth as a servant, nor as a threat. She orbited as a possibility — a future that could not coexist indefinitely with Earth’s own becoming. Two bodies could not remain forever in overlapping claims without resolution. Proximity demanded answer.",
      "And yet, for a time, they continued.",
      "They passed one another in the dark, close enough to alter tides that did not yet exist, close enough to whisper change into one another’s paths. Each encounter bent their orbits slightly, tightening the relationship even as it postponed its conclusion.",
      "Theia was not unaware.",
      "Not in thought, not in fear — but in presence. She felt the narrowing of paths, the loss of alternatives, the way remaining required more than motion. At the edge where drifting could still have saved her, Theia did not turn away. She held her course, not as decision, but as fidelity to what had already formed between them.",
      "In the language of myth, this would later be called knowing.",
      "To remain separate was to destabilize them both. To converge was to end herself — but not the story.",
      "She did not flee.",
      "She remained.",
      "And in remaining, she made the next movement inevitable."
    ]
  },
  {
    "label": "Movement III",
    "title": "The Orbit That Could Not Hold",
    "paragraphs": [
      "No orbit is forever.",
      "This is the quiet truth of the long fire: stability is borrowed, never owned. Paths that endure do so only until the balance of forces shifts, until proximity demands resolution.",
      "Earth and Theia had reached that threshold.",
      "They circled the Sun in neighboring lanes, their gravities threading through one another like hands brushing in passing. Each encounter altered what followed. Each near-miss tightened the weave. What had once been tolerance became tension. What had once been distance became insistence.",
      "Two bodies cannot share the same claim indefinitely.",
      "This was not malice. It was not error. It was geometry.",
      "The Sun’s pull held them both, but it could not decide between them. Earth’s mass bent Theia’s path; Theia’s momentum disturbed Earth’s restlessness. Their motions no longer resolved cleanly. The system demanded change.",
      "In later tellings, people would ask whether the collision was an accident.",
      "They would misunderstand the question.",
      "There are moments in the universe when separation becomes the greater violence. To remain near without resolution is to unravel slowly. To collide is to resolve at once.",
      "What drew Earth and Theia together was not desire, but fidelity to physics. Gravity does not choose — but it does not flee its consequences either. Nearness carries obligation. Proximity asks for answer.",
      "And so the paths narrowed.",
      "Theia’s orbit decayed, not in haste, but with certainty. Each pass carried her closer, each turn more aligned. Earth felt the approach as disruption — tides in molten seas, stress in a mantle not yet settled. Theia felt it as inevitability — a future that could not be avoided without undoing them both.",
      "This was not conquest.",
      "It was convergence.",
      "Earth did not reach outward to destroy. Theia did not rush inward to dominate. They met because no other configuration could last. Their closeness demanded transformation, and transformation required contact.",
      "If this is love, it is not gentle.",
      "It is the kind that accepts loss in order to preserve continuity. The kind that understands that survival sometimes requires one body to change completely so another may endure.",
      "The orbit could not hold.",
      "So it gave way.",
      "And in giving way, it made room for what would follow."
    ]
  },
  {
    "label": "Movement IV",
    "title": "The Embrace of Fire",
    "paragraphs": [
      "When Earth and Theia finally met, the meeting did not announce itself with sound.",
      "There was no shockwave to be heard, no thunder to mark the moment. In the vacuum of space, even catastrophe is silent. What followed unfolded instead as heat, motion, and irreversible change.",
      "Theia arrived at an angle — not headlong, not annihilating. A grazing embrace. Enough to tear, not enough to erase.",
      "Mantles collided.",
      "Rock liquefied in an instant. Stone lost its memory of solidity. What had been crust became current, what had been boundary became flow. Earth’s surface was stripped and reworked, her outer layers peeled back into incandescent motion. Theia’s body yielded more completely, her mass unspooled into Earth’s gravity and beyond.",
      "This was not destruction alone.",
      "It was redistribution.",
      "Earth endured by absorbing. Her core remained intact, anchoring her identity even as her skin was rewritten. Theia endured by transformation. She ceased to exist as a single body, but not as matter, not as influence. Her substance became trajectory, debris, future.",
      "A vast plume of fire and molten rock arced into orbit. Material that would never fall back rained outward instead, circling Earth in a glowing ring. What could not be held was not lost; it was given distance.",
      "The system was altered forever.",
      "And Earth reacted.",
      "Her grief had no language yet, no stillness in which to gather itself. It expressed instead as fury of process — heat without restraint, pressure without release. Volcanoes tore open the wounded surface again and again, pouring fire skyward as if the planet could burn away what had been taken from her. This was anger without intention, rage as motion, energy refusing to settle because nothing had yet taught it how.",
      "Stone cracked. Gases poured into the thickening sky. Steam rose and lingered, the atmosphere growing heavy with what Earth could not yet hold inside.",
      "Within Earth’s depths, the collision left signatures that would never fully fade. Asymmetries in the mantle, deep reservoirs of heat, slow-moving plumes rising from ancient wounds — scars not of failure, but of origin. Earth carried Theia within her now, not as memory alone, but as structure.",
      "Above, the debris ring burned.",
      "For a time, Earth wore a halo of fire — luminous, unstable, impossible to ignore. Fragments collided, shattered, reheated, collided again. Nothing there was whole, but nothing was still.",
      "This was the aftermath where creation learns patience.",
      "Earth did not mourn in that moment — not because there was nothing to mourn, but because mourning requires time, and time had not yet slowed. There was only consequence unfolding, matter negotiating new rules.",
      "The embrace had ended.",
      "But it had not finished speaking."
    ]
  },
  {
    "label": "Movement V",
    "title": "The Child Made of Distance",
    "paragraphs": [
      "From the ring of fire, wholeness did not come at once.",
      "The debris that circled Earth was too close to be free, too distant to return. Gravity held it in tension, forbidding collapse near the planet while allowing gathering farther out. This boundary — invisible, unforgiving — marked the place where fragments could finally become more than themselves.",
      "Beyond that limit, matter began to listen.",
      "Grain by grain, shard by shard, the scattered remains of Earth and Theia found one another. Heat bled away. Motion synchronized. Collisions softened from violence into adhesion. What had been chaos learned repetition, and repetition learned form.",
      "A body emerged.",
      "Not captured. Not commanded.",
      "Born.",
      "The Moon condensed slowly, patiently, assembling herself from what had been given distance. She carried Earth’s mantle and Theia’s transformed substance, memory without consciousness, lineage without hierarchy. She was not a replacement for what had been lost. She was what loss made possible.",
      "Below her, Earth continued to change.",
      "As fire spent itself, the thickened sky could no longer hold what it carried. Steam cooled. Clouds gathered. Rain began to fall — not gently, not briefly, but endlessly. Water returned to the surface again and again, as if Earth were repeating a question she did not yet know how to stop asking.",
      "This was not relief.",
      "It was bargaining.",
      "Cycles formed before purpose. Rain fell, evaporated, fell again. The planet rehearsed stability without trusting it. Earth tried, over and over, to regulate what could not be undone, to soften what had already happened.",
      "In time, repetition became weight.",
      "Water ceased to vanish. It pooled. It stayed.",
      "Basins filled. Lowlands darkened. Oceans gathered where tears had fallen long enough to change the ground beneath them. Earth’s grief settled into depth — no longer eruptive, no longer pleading, but present everywhere. The planet slowed further, her surface dimming, her heat sinking inward.",
      "This was not despair.",
      "It was depression — heaviness accepted, loss carried rather than resisted.",
      "And still, above her, the Moon was forming.",
      "In her earliest days, the Moon was close.",
      "She loomed vast in Earth’s sky, luminous and unfinished, her surface still molten, her shape still settling. Her gravity reached inward, kneading Earth’s restless seas, pulling at water and stone alike. Earth responded by slowing. Rotation lengthened. Time stretched its first long breath.",
      "This was their first conversation.",
      "Earth gave momentum.",
      "The Moon gave rhythm.",
      "Tides rose and fell, again and again, now water answering water. In this exchange, Earth cooled. Her surface stabilized. Crust thickened. Atmosphere lingered. Life’s conditions gathered quietly, nurtured by rhythm born of loss.",
      "The Moon watched.",
      "She watched Earth’s fire dim, watched oceans darken and deepen, watched continents begin their slow negotiations. She watched one mother endure, and the other persist everywhere — diffused through mantle and motion, present without form.",
      "As time passed, distance grew.",
      "The Moon began to recede, centimeter by centimeter, not as abandonment but as maturation. Nearness was no longer required for conversation. The bond held across space. Gravity carried memory better than touch.",
      "The Moon learned to be apart.",
      "And Earth learned, slowly, to live while carrying what she had lost."
    ]
  },
  {
    "label": "Epilogue",
    "title": "The Ongoing Answer",
    "paragraphs": [
      "The Moon still circles.",
      "She has done so for longer than memory, longer than language, longer than any story that tries to hold her. Her path has widened with time, her pace slowed, her closeness softened into constancy. Distance has not weakened the bond; it has made it durable.",
      "Earth continues to change beneath her.",
      "Oceans rise and fall in the Moon’s keeping. Continents drift, collide, and part again. Mountains lift and erode. Life emerges, fails, returns, and learns to look upward. Through all of it, Earth carries within her the deep signatures of her making — the transformed presence of Theia, still shaping heat and stone from below.",
      "Nothing that was given has vanished.",
      "Theia is not gone. She is everywhere Earth is warm, everywhere stone moves slowly, everywhere the planet remembers how to endure change. Earth did not lose a companion; she absorbed one. The Moon did not lose a parent; she gained a lineage written into gravity itself.",
      "The Sun still burns.",
      "Not as ruler, not as judge, but as source — the long fire that makes motion possible and consequence inevitable. From its light come gradients, from gradients come worlds, and from worlds come stories. The Sun does not command the family of planets. It holds them in being by continuing to give what it cannot withhold.",
      "This is not a story of perfection.",
      "It is a story of balance learned slowly, of violence transformed into continuity, of closeness surrendered so that relationship may endure. Creation here is not a moment completed, but a process still answering itself.",
      "The Moon watches.",
      "She watches Earth age, watches life learn fragility and resilience, watches intelligence awaken and wonder where it came from. She offers no instruction, only presence — a reminder that nothing whole is born without loss, and nothing lost is ever truly gone.",
      "The conversation continues.",
      "Gravity still speaks. Tides still answer. Distance still grows, carrying memory forward rather than away.",
      "And in that ongoing answer — in orbit, in rhythm, in light borrowed and returned — the family endures."
    ]
  }
] as const;
