export const ASSESSMENT_VERSION_V2 = "immigration-v2";
export const SCORED_QUESTION_COUNT = 100;
export const QUESTIONS_PER_CATEGORY = 10;
export const CATEGORY_PASSING_SCORE = 7;
export const OVERALL_PASSING_SCORE = 90;

export const assessmentCategories = [
  { key: "founding-covenant", label: "Founding Covenant" },
  { key: "constitutional-rights-duties", label: "Constitutional Rights and Duties" },
  { key: "governance-circle-system", label: "Governance and Circle System" },
  { key: "learning-contribution", label: "Learning and Contribution" },
  { key: "care-consent-autonomy", label: "Care, Consent, and Bodily Autonomy" },
  { key: "harm-restoration-harmony", label: "Harm, Restoration, and Harmony" },
  { key: "stewardship-capacity-balance", label: "Stewardship, Capacity, and Balance" },
  { key: "immigration-civic-standing", label: "Immigration and Civic Standing" },
  { key: "time-continuity-observance", label: "Time, Continuity, and Observance" },
  { key: "public-civic-practice", label: "Public Civic Practice" },
];

function concept(category, id, prompt, correct, distractors, explanation, sourceSlug, sourceSection) {
  return { category, id: `${category}-${id}`, prompt, correct, distractors, explanation, sourceSlug, sourceSection };
}

const concepts = [
  concept("founding-covenant", "01", "What makes membership in the Utopian Society legitimate?", "A voluntary civic covenant entered with informed consent", ["An inherited claim through ancestry", "A purchase made through wealth", "A permanent obligation imposed at birth"], "Belonging is chosen and remains meaningful only while peaceful exit is protected.", "the-charter-of-the-utopian-society", "The Civic Covenant"),
  concept("founding-covenant", "02", "What relationship does the Declaration establish between dignity and productivity?", "Human dignity is inherent and cannot be earned through productivity", ["Dignity rises with economic output", "Only officers possess civic dignity", "Dignity depends on physical capacity"], "The founding texts reject any measure of human worth based on output, status, or capacity.", "declaration-of-existence", "Human dignity"),
  concept("founding-covenant", "03", "Which principle governs the interpretation of every daughter document?", "The founding ethic of autonomy, consent, care, balance, truth, and non-harm", ["The preference of the largest Circle", "The oldest custom regardless of harm", "The private interest of current officers"], "Daughter documents may refine the framework but may not contradict its constitutional foundation.", "article-i-foundation", "Sacred Principles"),
  concept("founding-covenant", "04", "What does the Society mean by transparency?", "Civic power and decisions remain open to public examination", ["Every private detail becomes public", "Officers may conceal inconvenient records", "Only final outcomes may be disclosed"], "Transparency illuminates institutions without abolishing personal privacy.", "article-i-foundation", "Transparency"),
  concept("founding-covenant", "05", "How does the Society treat human error?", "As an occasion for accountability, learning, and possible renewal", ["As proof of permanent corruption", "As irrelevant whenever intent was good", "As grounds for inherited stigma"], "Balance over purity allows repair without excusing harm.", "article-i-foundation", "Balance over Purity"),
  concept("founding-covenant", "06", "What is the naturalist adaptation of the Golden Rule?", "Treat others as they wish to be treated when doing so causes no harm", ["Treat everyone exactly as you prefer", "Obey custom even when consent is absent", "Avoid responsibility for another person's boundaries"], "Empathy must attend to another person's actual needs and boundaries.", "article-i-foundation", "Golden Rule"),
  concept("founding-covenant", "07", "Why is truth described as sacred?", "Because civic trust depends on honest words, records, and conduct", ["Because only officials may define reality", "Because disagreement must be prohibited", "Because private thought must be inspected"], "Truth is a daily civic practice that makes accountable cooperation possible.", "article-i-foundation", "Truth as Sacred"),
  concept("founding-covenant", "08", "What does care contribute to governance?", "It gives law and duty their humane purpose", ["It replaces all evidence and procedure", "It permits favoritism toward friends", "It makes public accountability unnecessary"], "Care and love animate civic structures but do not erase truth or due process.", "article-i-foundation", "Care and Love"),
  concept("founding-covenant", "09", "When the letter and spirit of a rule appear to conflict, what should guide interpretation?", "The constitutional principles protecting consent, care, Earth, balance, and truth", ["The harshest possible reading", "The interpretation producing the most revenue", "The preference of whoever filed first"], "The Constitution is a living covenant whose protective spirit governs interpretation.", "article-i-foundation", "Binding Force"),
  concept("founding-covenant", "10", "What freedom makes a voluntary society remain voluntary over time?", "The peaceful right to leave", ["The right to inherit office", "The right to conceal public decisions", "The right to compel another's contribution"], "Consent to belong is ongoing rather than irrevocable.", "article-ii-membership-citizenship", "Right of Exit"),

  concept("constitutional-rights-duties", "01", "What is the relationship between rights and duties?", "Rights protect dignity while duties sustain the conditions in which everyone can exercise them", ["Duties cancel rights during inconvenience", "Rights belong only to contributors", "Duties are optional for public officers"], "The Constitution joins liberty with reciprocal responsibility.", "article-iii-rights-freedoms", "Rights and Freedoms"),
  concept("constitutional-rights-duties", "02", "Who is steward of an individual's body and medical choices?", "The individual, subject to informed capacity and non-coercion", ["The Circle of Healing", "The majority of nearby citizens", "The person's contribution supervisor"], "Healing protects care access while bodily autonomy remains with the person.", "article-viii-continuance-medical-ethics", "Medical autonomy"),
  concept("constitutional-rights-duties", "03", "What kind of agreement qualifies as consent?", "Informed, specific, affirmative, ongoing, and retractable agreement", ["Silence when refusal feels risky", "A permanent permission inferred from history", "Agreement supplied by an unrelated officer"], "Consent is invalid when coercion, fraud, incapacity, or undue influence defeats free choice.", "article-i-foundation", "Consent"),
  concept("constitutional-rights-duties", "04", "What does freedom of expression not permit?", "Coercion, targeted harm, or the destruction of another person's equal rights", ["Good-faith criticism of institutions", "Peaceful artistic experimentation", "Disagreement with a civic proposal"], "Freedom is broad but does not become authority to dominate others.", "article-iii-rights-freedoms", "Expression and equal dignity"),
  concept("constitutional-rights-duties", "05", "How should civic duties account for disability, illness, or changing capacity?", "Duties adapt to actual ability without reducing human worth", ["The person loses civic standing", "The person must meet the same physical output", "Care is withheld until productivity returns"], "Contribution follows capacity; dignity does not.", "article-iv-duties-responsibilities", "Contribution according to ability"),
  concept("constitutional-rights-duties", "06", "What is required before public power may restrict a person?", "A lawful purpose, fair procedure, evidence, and proportionate safeguards", ["A private suspicion", "A permanent emergency declaration", "The request of any single Circle"], "Constitutional power is bounded by due process and review.", "article-v-justice-resolution", "Justice and Resolution"),
  concept("constitutional-rights-duties", "07", "What does environmental stewardship require of citizens and institutions?", "Living within regenerative limits and repairing ecological damage", ["Maximizing extraction before scarcity", "Treating Earth as ownerless inventory", "Delegating all responsibility to Custodianship"], "Earth stewardship is a shared constitutional duty administered through public systems.", "article-xiii-environmental-stewardship", "Environmental Stewardship"),
  concept("constitutional-rights-duties", "08", "How does the Constitution treat access to learning?", "As a lifelong civic right available through changing seasons of life", ["As a childhood privilege only", "As a reward reserved for officers", "As a debt purchased from private institutions"], "Citizens may learn, unlearn, retrain, deepen mastery, or begin again.", "article-xii-education-learning", "Education and Learning"),
  concept("constitutional-rights-duties", "09", "Which condition is forbidden in legitimate civic service?", "Torture or coercive domination", ["Transparent readiness training", "Civil resilience planning", "Constitutional review of defensive action"], "Protection cannot be built by violating the dignity it exists to defend.", "article-xx-prohibition-of-weapons-and-torture", "Prohibitions"),
  concept("constitutional-rights-duties", "10", "What duty accompanies access to public records?", "To use them responsibly without exposing protected personal information", ["To publish every private detail", "To alter records that seem embarrassing", "To conceal institutional decisions"], "Transparency and privacy are complementary civic obligations.", "article-iii-rights-freedoms", "Privacy and transparency"),

  concept("governance-circle-system", "01", "How many Foundational Circles are recognized in Constitution Draft v2.2?", "Seven", ["Four", "Six", "Eight including Time"], "The seven are Contribution, Learning, Healing, Harmony, Custodianship, Balance, and Defense.", "article-xvii-governance-structure-circles", "Seven Foundational Circles"),
  concept("governance-circle-system", "02", "Is Utopian Reference Time an eighth Foundational Circle?", "No; it is a shared constitutional instrument", ["Yes; the clock votes in Council", "Yes; every calendar is a Circle", "No; time has no civic role"], "Time and Observance is stewarded collectively and experienced through the central calendar.", "charter-of-time-and-observance", "Shared instrument"),
  concept("governance-circle-system", "03", "What authority may a Council exercise?", "Independent domain authority within its Circle and constitutional boundaries", ["Unlimited authority over every Circle", "Advisory speech with no domain authority", "Authority to override the Constitution"], "A Council governs its assigned intra-Circle domain but cannot escape the wider weave.", "article-xvii-governance-structure-circles", "Councils"),
  concept("governance-circle-system", "04", "What distinguishes an Operational Circle from a Foundational Circle?", "It implements a specialized bounded Charter or Codex mandate", ["It possesses greater human dignity", "It is exempt from public accountability", "It exists only during emergencies"], "Operational bodies remain important without becoming society-wide constitutional mandates.", "article-xvii-governance-structure-circles", "Operational Circles"),
  concept("governance-circle-system", "05", "What happens to a Temporary Ring when its defined task or crisis ends?", "It dissolves automatically", ["It becomes a permanent government", "It inherits the Council of Seasons", "It may continue without review"], "Temporary authority is time-limited and cannot quietly become permanent.", "article-xvii-governance-structure-circles", "Temporary Rings"),
  concept("governance-circle-system", "06", "Which Circle owns mediation, restoration, and peaceful dispute resolution?", "Harmony", ["Defense", "Contribution", "Custodianship"], "Harmony has distinct jurisdiction over harm and restorative process.", "article-xiv-governance-framework", "Circle of Harmony"),
  concept("governance-circle-system", "07", "Which Circle owns care access, medical ethics, and provider standards?", "Healing", ["Balance", "Learning", "Custodianship"], "Healing is foundational because health and bodily autonomy require continuous independent authority.", "article-xiv-governance-framework", "Circle of Healing"),
  concept("governance-circle-system", "08", "What is the Council of Seasons?", "A rotating cross-Circle coordinating council", ["A permanent executive ruler", "A weather service without governance purpose", "A private council of former officers"], "Coordination does not erase the independent jurisdiction of each Circle.", "article-xiv-governance-framework", "Council of Seasons"),
  concept("governance-circle-system", "09", "How is a genuine tie among equally eligible civic candidates resolved?", "By lot after eligibility, rotation, and qualification are established", ["By inherited rank", "By wealth", "By permanent appointment"], "Lot is a narrow tie-breaker rather than the primary method of selection.", "article-xv-circle-formation-and-civic-representation", "Selection and lot"),
  concept("governance-circle-system", "10", "May one Circle unilaterally absorb another Circle's jurisdiction?", "No; jurisdiction changes require constitutional process", ["Yes, whenever it has more members", "Yes, during any ordinary meeting", "Yes, if it controls infrastructure"], "Peer Circles have bounded mandates and equal civic dignity.", "article-xvii-governance-structure-circles", "Jurisdictional boundaries"),

  concept("learning-contribution", "01", "What is the purpose of lifelong learning?", "To keep knowledge, vocation, judgment, and civic participation capable of renewal", ["To lock each person into a first occupation", "To rank citizens permanently", "To replace lived experience with tests"], "Learning is a continuing civic ecology rather than a one-time credential.", "article-xii-education-learning", "Lifelong Learning"),
  concept("learning-contribution", "02", "How does the Society define meaningful contribution?", "Participation suited to ability that sustains shared life", ["Maximum output regardless of harm", "Only paid industrial labor", "A score measuring human worth"], "Care, craft, study, art, maintenance, research, and many other forms can contribute.", "circle-of-contribution-charter", "Meaningful Contribution"),
  concept("learning-contribution", "03", "What does the Social Equilibrium Principle adjust?", "Recognition for burden, scarcity, strain, and civic need without pricing human worth", ["A citizen's dignity", "Voting rights", "Access to essential care"], "SEP helps balance contribution conditions while preserving equality.", "circle-of-contribution-charter", "Social Equilibrium Principle"),
  concept("learning-contribution", "04", "What should happen when a citizen's capacity changes?", "Their contribution pathway should be reviewed and adapted", ["Their citizenship ends", "Their prior learning is erased", "Their basic needs become conditional"], "Contribution and Learning cooperate so roles can change without stigma.", "circle-of-contribution-charter", "Capacity and reassignment"),
  concept("learning-contribution", "05", "What role does the Utopian Society University play?", "It distributes learning through civic life, practice, mentorship, and inquiry", ["It confines knowledge to one building", "It sells permanent social rank", "It replaces every Circle"], "The University is a Tree of Knowledge embedded throughout society.", "circle-of-learning-charter", "Utopian Society University"),
  concept("learning-contribution", "06", "What are Collegia?", "Sector-linked bodies preserving knowledge and training practice ethically", ["Hereditary guilds controlling citizenship", "Temporary military courts", "Private markets for civic office"], "Collegia connect practical contribution with mentorship, archives, and innovation.", "article-i-foundation", "Definitions: Collegium"),
  concept("learning-contribution", "07", "May a citizen retrain for a new vocation?", "Yes, at any season of life", ["No, the first assignment is permanent", "Only after surrendering civic rights", "Only if the former sector approves ownership"], "A vocation is a path, not a sentence.", "circle-of-learning-charter", "Retraining"),
  concept("learning-contribution", "08", "Why must Contribution consult Learning?", "Sector needs may require education, apprenticeship, or retraining", ["Learning controls every work decision", "Contribution may ignore skill development", "Consultation makes records secret"], "The Circles coordinate where labor needs meet human development.", "article-xvi-governance-of-sectors-contribution", "Cross-Circle consultation"),
  concept("learning-contribution", "09", "What should affirmation of completed contribution verify?", "That the described work occurred and met transparent criteria", ["That the citizen is more valuable", "That an officer personally approves of the citizen", "That all future work is compulsory"], "Affirmation records truth without creating status hierarchy.", "circle-of-affirmation-charter", "Verification and recognition"),
  concept("learning-contribution", "10", "What protects a citizen from exploitative contribution demands?", "Consent, capacity review, rest, safety, and restorative challenge", ["Silence", "Permanent assignment", "Loss of essential services"], "Contribution is reciprocal civic participation, not coerced labor.", "circle-of-contribution-charter", "Consent and obligation"),

  concept("care-consent-autonomy", "01", "Which four dimensions belong to whole-person care?", "Physical, mental and emotional, sexual and reproductive, and social and relational", ["Productive, punitive, financial, and military", "Private, commercial, hereditary, and ceremonial", "Medical, electoral, judicial, and industrial"], "Healing treats health as an interdependent whole.", "circle-of-healing-charter", "Whole-person care"),
  concept("care-consent-autonomy", "02", "May a competent person refuse recommended treatment?", "Yes; informed refusal is part of bodily autonomy", ["No; providers own the decision", "Only if a majority agrees", "Only after losing access to future care"], "Access to care does not turn care into coercion.", "circle-of-healing-charter", "Consent and refusal"),
  concept("care-consent-autonomy", "03", "What information should be provided before medical consent?", "Purpose, material risks, benefits, alternatives, and the option to refuse", ["Only the provider's preferred outcome", "No information if treatment is common", "Private opinions about the patient's worth"], "Consent requires understandable and relevant information.", "article-viii-continuance-medical-ethics", "Informed medical choice"),
  concept("care-consent-autonomy", "04", "Who may access a citizen's private health details?", "Only authorized participants for a legitimate care purpose", ["Every visitor to the public ledger", "Any contribution supervisor", "Anyone curious about the outcome"], "Healing must combine continuity of care with strict privacy.", "circle-of-healing-charter", "Privacy"),
  concept("care-consent-autonomy", "05", "How is sexual and reproductive health treated?", "As an ordinary, dignified part of whole-person health", ["As grounds for public shame", "As outside the Circle of Healing", "As a privilege available only after marriage"], "The Society approaches sexual wellbeing through consent, evidence, and dignity.", "sexual-expression-codex", "Health and wellbeing"),
  concept("care-consent-autonomy", "06", "What invalidates sexual consent?", "Coercion, incapacity, fraud, intimidation, or withdrawn willingness", ["A partner asking a clarifying question", "A person setting a boundary", "A mutually desired pause"], "Consent must remain free, specific, and present.", "sexual-expression-codex", "Consent"),
  concept("care-consent-autonomy", "07", "What is the role of a Healing practitioner?", "To support informed choices without taking ownership of the person's body", ["To compel the optimal treatment", "To report all private details publicly", "To decide a citizen's civic worth"], "Practitioners provide knowledge, skill, care, and safeguards within consent.", "circle-of-healing-charter", "Provider standards"),
  concept("care-consent-autonomy", "08", "How should the Society respond to a person temporarily lacking decision-making capacity?", "Use the least restrictive safeguards while preserving dignity and prior wishes", ["Erase all future autonomy", "Transfer permanent ownership to an officer", "Publish the condition as punishment"], "Capacity safeguards protect rather than replace personhood.", "article-viii-continuance-medical-ethics", "Capacity safeguards"),
  concept("care-consent-autonomy", "09", "Does access to essential care depend on CCU balance?", "No; essential care is a right rather than an enrichment purchase", ["Yes, every treatment is a market good", "Only officers receive care without credits", "Care depends on productivity rank"], "The civic economy cannot condition fundamental health access on wealth.", "circle-of-healing-charter", "Universal care access"),
  concept("care-consent-autonomy", "10", "Why does Healing coordinate with Learning?", "Health literacy and provider education protect informed autonomy", ["Learning decides treatment", "Healing controls every curriculum", "Coordination removes confidentiality"], "Knowledge helps citizens interpret choices and helps practitioners maintain standards.", "circle-of-healing-charter", "Health education"),

  concept("harm-restoration-harmony", "01", "Which framework replaces deprecated Criminal Codex language?", "The Restoration Codex", ["The Punishment Codex", "The Defense Charter", "The Contribution Ledger"], "Current continuity uses restorative rather than criminalizing terminology.", "restoration-codex", "Continuity of language"),
  concept("harm-restoration-harmony", "02", "What is Harmony's primary jurisdiction?", "Harm, mediation, restoration, procedural justice, and peaceful dispute resolution", ["Medical diagnosis", "Ecological infrastructure", "Sector assignment"], "Harmony owns the processes by which conflict is heard and repair is pursued.", "circle-of-harmony-charter", "Jurisdiction"),
  concept("harm-restoration-harmony", "03", "What is the first purpose of a harm report?", "To make the alleged harm safely hearable and begin appropriate triage", ["To publicly declare guilt", "To guarantee punishment", "To expose every private detail"], "Intake begins process; it is not a final judgment.", "circle-of-harmony-charter", "Harm intake"),
  concept("harm-restoration-harmony", "04", "What does restorative accountability require from a person who caused harm?", "Truthful acknowledgment, meaningful repair, and changed conduct", ["A performance of shame without repair", "Automatic permanent exile", "Silence if intent was good"], "Restoration joins accountability with a credible path back toward trust.", "restoration-codex", "Accountability and repair"),
  concept("harm-restoration-harmony", "05", "Does reconciliation always require renewed closeness between participants?", "No; safety and repair may require distance or firm boundaries", ["Yes, forgiveness requires intimacy", "Yes, the harmed person must resume contact", "No, because repair is never possible"], "Restoration does not compel emotional access or erase protective boundaries.", "restoration-codex", "Boundaries and restoration"),
  concept("harm-restoration-harmony", "06", "What must a fair proceeding provide?", "Notice, a meaningful chance to be heard, impartial facilitation, and reviewable reasons", ["A secret accusation and immediate outcome", "Authority based on popularity", "A decision without evidence"], "Procedural justice protects all participants while centering safety.", "circle-of-harmony-charter", "Procedural safeguards"),
  concept("harm-restoration-harmony", "07", "How should a public proceedings calendar protect privacy?", "Publish procedural timing and type without unnecessary personal details", ["Publish all testimony in advance", "Hide whether proceedings exist", "Identify private health information"], "The public may see that civic process occurs without turning harm into spectacle.", "circle-of-harmony-charter", "Proceedings calendar"),
  concept("harm-restoration-harmony", "08", "When may protective separation be appropriate?", "When proportionate safeguards are needed to prevent further harm during review", ["Whenever an officer dislikes criticism", "As a permanent substitute for process", "Only after public shaming"], "Interim protection must be necessary, bounded, and reviewable.", "restoration-codex", "Protective measures"),
  concept("harm-restoration-harmony", "09", "Who determines the outcome of a Harmony proceeding?", "Authorized human civic decision-makers following evidence and procedure", ["An unsupervised AI model", "The loudest observer", "A random public poll"], "AI may assist organization but cannot replace accountable human judgment.", "circle-of-harmony-charter", "Human authority"),
  concept("harm-restoration-harmony", "10", "What should happen when new evidence reveals a material procedural error?", "The decision should be reviewable through the established appeal process", ["The evidence must be ignored", "The entire record must be destroyed", "The facilitator gains permanent authority"], "Restorative legitimacy depends on the ability to correct process failures.", "restoration-codex", "Review and appeal"),

  concept("stewardship-capacity-balance", "01", "What is the Circle of Balance responsible for?", "Systemic capacity, equilibrium, long-range risk, and competing civic needs", ["Personal medical treatment", "Every mediation proceeding", "All education curricula"], "Balance examines the whole system without absorbing other Circles' domains.", "circle-of-balance-charter", "Jurisdiction"),
  concept("stewardship-capacity-balance", "02", "What is Custodianship responsible for?", "Land, ecology, infrastructure, energy, water, transport, housing systems, and archives", ["Military command", "Individual medical consent", "Immigration interviews alone"], "Custodianship maintains the shared physical and ecological commons.", "article-xiv-governance-framework", "Custodianship"),
  concept("stewardship-capacity-balance", "03", "What does a population capacity ceiling protect?", "Ecological and civic systems from being pushed beyond sustainable limits", ["A preferred ancestry", "Permanent exclusion from membership", "The authority of a single officer"], "Capacity is a condition of humane stewardship, not a judgment of applicant worth.", "immigration-codex", "Population stewardship"),
  concept("stewardship-capacity-balance", "04", "What is an operational population buffer?", "A deliberate margin below maximum capacity", ["A secret list of applicants", "A reserve of political offices", "A penalty imposed on large households"], "The buffer lets the Society absorb births, emergencies, and system strain.", "immigration-codex", "Operational Population Buffer"),
  concept("stewardship-capacity-balance", "05", "Under the limiting-resource principle, what sets the practical population ceiling?", "The essential resource nearest its sustainable limit", ["The most abundant resource", "The number of applications", "The largest Circle"], "Overall capacity is constrained by the system with the least safe remaining margin.", "immigration-codex", "Limiting-resource principle"),
  concept("stewardship-capacity-balance", "06", "How should a capacity indicator communicate uncertainty?", "By publishing its method, evidence, confidence, and limitations", ["By displaying one unexplained number", "By hiding unfavorable measurements", "By treating estimates as permanent law"], "Transparent uncertainty makes systemic review more honest and useful.", "circle-of-balance-charter", "Indicators and methodology"),
  concept("stewardship-capacity-balance", "07", "Who owns routine infrastructure maintenance decisions?", "Custodianship within its assigned public-systems domain", ["Harmony", "Immigration", "A temporary Crisis Ring forever"], "Balance may review systemic effects, but Custodianship operates the infrastructure domain.", "article-xiv-governance-framework", "Jurisdictional boundaries"),
  concept("stewardship-capacity-balance", "08", "What does closed-loop industry forbid?", "Planned obsolescence and unmanaged waste", ["Repair and reuse", "Material accounting", "Design for long service"], "Outputs should return as inputs wherever possible.", "article-xiii-environmental-stewardship", "Closed-loop industry"),
  concept("stewardship-capacity-balance", "09", "When two essential civic needs compete for the same scarce resource, which Circle coordinates equilibrium review?", "Balance", ["Affirmation", "Learning alone", "The applicant who arrived first"], "Balance weighs cross-system consequences while domain Circles provide expertise.", "circle-of-balance-charter", "Competing civic needs"),
  concept("stewardship-capacity-balance", "10", "What is the Continuance review meant to assess?", "Long-range ethical, demographic, medical, and resource consequences", ["A citizen's social popularity", "A permanent right to unlimited resources", "A substitute for informed medical consent"], "Continuance decisions require cross-Circle review because they affect both person and system.", "article-viii-continuance-medical-ethics", "Continuance"),

  concept("immigration-civic-standing", "01", "Who is a Hopeful?", "A person who has formally entered membership evaluation", ["A full citizen", "A permanent resident", "A hereditary officeholder"], "Hopeful status recognizes aspiration without pretending the pathway is complete.", "immigration-codex", "Civic classifications"),
  concept("immigration-civic-standing", "02", "What is the purpose of Residency?", "Mutual evaluation through lived participation before full constitutional citizenship", ["A punitive probation", "Immediate legal nationality", "A way to bypass capacity review"], "Residency allows both the person and Society to test long-term fit in practice.", "immigration-codex", "Residency"),
  concept("immigration-civic-standing", "03", "What does the online certificate grant?", "Virtual symbolic recognition only", ["Legal nationality", "Physical residence", "Completion of the constitutional Residency Pathway"], "The portal must not misrepresent symbolic participation as state nationality.", "immigration-codex", "Online symbolic recognition"),
  concept("immigration-civic-standing", "04", "What does passing the civic assessment demonstrate?", "Comprehension of the civic framework", ["Perfect ideological conformity", "Human worth", "Guaranteed physical admission"], "The assessment tests understanding rather than identity or value.", "immigration-codex", "Civic comprehension"),
  concept("immigration-civic-standing", "05", "May wealth purchase priority admission?", "No", ["Yes, if infrastructure is needed", "Yes, for relatives of citizens", "Yes, if the payment is private"], "Admission cannot be purchased or inherited.", "immigration-codex", "Equal consideration"),
  concept("immigration-civic-standing", "06", "What happens when a qualified Hopeful is deferred solely because capacity is unavailable?", "The application may be reconsidered when capacity returns", ["The person is permanently rejected", "Citizenship is automatic next cycle", "All records are erased"], "Capacity deferral is not a judgment of personal worth or compatibility.", "immigration-codex", "Deferral"),
  concept("immigration-civic-standing", "07", "Why do multiple Circles participate in immigration review?", "To include relevant expertise and prevent unilateral control", ["To conceal responsibility", "To guarantee every application", "To make standards unpredictable"], "Distributed review makes the process more balanced and accountable.", "immigration-codex", "Multi-Circle review"),
  concept("immigration-civic-standing", "08", "Who is an Independent?", "A former citizen who has peacefully relinquished civic membership", ["A Hopeful awaiting interview", "A resident without housing", "A visitor to the University"], "Independent standing preserves the right of exit while clarifying the civic record.", "immigration-codex", "Independent standing"),
  concept("immigration-civic-standing", "09", "What should an immigration denial include?", "An understandable reason and available review pathway", ["No explanation", "An ancestry ranking", "Automatic public exposure of private details"], "Reviewable reasons are part of respectful due process.", "immigration-codex", "Determinations and appeal"),
  concept("immigration-civic-standing", "10", "What is a Transient?", "A person present temporarily for a defined exchange or contribution purpose", ["A full citizen", "A person forbidden to apply", "A permanent resident with inherited office"], "Temporary standing serves defined needs without becoming an indirect permanent route.", "immigration-codex", "Transient standing"),

  concept("time-continuity-observance", "01", "What is the center of the frontispiece intended to represent?", "Utopian Reference Time as a shared living civic measure", ["An eighth governing Circle", "A decorative clock with no meaning", "The authority of the Council of Seasons"], "Time forms the shared axis around which the corpus and civic life turn.", "charter-of-time-and-observance", "Reference Time"),
  concept("time-continuity-observance", "02", "How many named Utopian months form an ordinary year?", "Thirteen", ["Twelve", "Ten", "Fourteen"], "Each of the thirteen months contains four equal weeks.", "charter-of-time-and-observance", "Months"),
  concept("time-continuity-observance", "03", "How many days are in an ordinary Utopian month?", "Twenty-eight", ["Thirty", "Thirty-one", "Twenty-five"], "Four seven-day weeks create equal civic months.", "charter-of-time-and-observance", "Equal months"),
  concept("time-continuity-observance", "04", "What is the Bridging?", "A period beyond the thirteen equal months that reconciles the solar year", ["A hidden fourteenth Circle", "A military emergency", "A pause in citizenship rights"], "The Bridging keeps the calendar aligned without distorting the equal months.", "charter-of-time-and-observance", "The Bridging"),
  concept("time-continuity-observance", "05", "Does a Utopian weekday always match the local Gregorian weekday?", "No; it follows the Society's own epoch and repeating week", ["Yes, the names are direct translations", "Only during the Bridging", "Only for officers"], "Utopian weekday names belong to an independent calendar sequence.", "charter-of-time-and-observance", "Weekdays"),
  concept("time-continuity-observance", "06", "Which time standard anchors the Society's shared clock?", "UTC", ["The browser's local time", "One founder's home timezone", "A random regional offset"], "UTC gives a common reference independent of a visitor's location.", "charter-of-time-and-observance", "UTC reference"),
  concept("time-continuity-observance", "07", "Are civic observances compulsory acts of belief?", "No; participation remains voluntary and observances serve memory and continuity", ["Yes, refusal ends citizenship", "Yes, officers prescribe private belief", "No, because observances are forbidden"], "Shared remembrance cannot legitimately become coerced conscience.", "charter-of-time-and-observance", "Voluntary observance"),
  concept("time-continuity-observance", "08", "Why should documents show Created and Last Updated dates in Utopian form?", "To make the Society's own civic chronology primary and traceable", ["To conceal when changes occurred", "To prevent Gregorian reference", "To give documents legal nationality"], "Utopian dates establish continuity while Gregorian dates may remain secondary references.", "charter-of-time-and-observance", "Civic dating"),
  concept("time-continuity-observance", "09", "What is Utopian Year 1 relative to the founding epoch?", "The first civic year beginning at the established epoch, not a Year 0", ["A zero-indexed technical year", "The year before the Society existed", "A label that changes by timezone"], "The public clock and documents use Year 1 for the founding civic year.", "charter-of-time-and-observance", "Founding epoch"),
  concept("time-continuity-observance", "10", "What should happen when a calendar conversion rule and published Charter conflict?", "The rule and Charter should be reconciled transparently with a dated correction", ["The discrepancy should be hidden", "The browser's local result automatically wins", "Every prior date should be silently deleted"], "Continuity requires one authoritative method and a visible revision trail.", "charter-of-time-and-observance", "Continuity and correction"),

  concept("public-civic-practice", "01", "What belongs in the public Transparency Ledger?", "Meaningful civic events, decisions, and corrections with accountable provenance", ["Every private conversation", "Unverified rumors", "Secretly altered summaries"], "The ledger documents public civic action without abolishing privacy.", "article-i-foundation", "Transparency"),
  concept("public-civic-practice", "02", "How is an error in an immutable ledger corrected?", "By appending a linked correction rather than rewriting history", ["By deleting the original entry", "By changing the database silently", "By hiding both records"], "Append-only correction preserves both accountability and context.", "article-i-foundation", "Transparent records"),
  concept("public-civic-practice", "03", "Which name should represent the founder in Utopian Society civic records?", "Adreto Nagdo Senoviros", ["A private legal name", "An anonymous placeholder", "A different name on each entry"], "Civic identity is consistent, intentional, and separate from unnecessary legal identity.", "about", "Civic identity"),
  concept("public-civic-practice", "04", "What should a citizen portal show first?", "A coherent view of the citizen's standing, learning, contribution, CCUs, residence, and civic matters", ["Only advertising", "Private records of other citizens", "A permanent error log"], "The portal situates a person within the shared civic system.", "about", "Citizen-facing civic portal"),
  concept("public-civic-practice", "05", "When may AI assist a civic proceeding?", "By organizing information or explaining procedure under human authority", ["By issuing unsupervised binding judgment", "By inventing missing evidence", "By concealing its role"], "Accountable humans retain civic authority and responsibility.", "circle-of-harmony-charter", "Human decision authority"),
  concept("public-civic-practice", "06", "What does an idempotency key protect against?", "Accidental duplicate civic writes when a request is retried", ["Public access to published records", "The need for authentication", "The right to append corrections"], "A retried action should create one assignment, transaction, certificate, or ledger event.", "article-i-foundation", "Reliable transparent administration"),
  concept("public-civic-practice", "07", "How should essential services differ from enrichment goods in the CCU system?", "Essential rights remain available regardless of balance; CCUs govern optional enrichment exchange", ["Both require positive balances", "Only officers receive essentials", "Enrichment goods are compulsory"], "The civic economy may coordinate scarcity without monetizing dignity or survival.", "circle-of-contribution-charter", "CCUs and essential provision"),
  concept("public-civic-practice", "08", "What should happen before a civic request changes official standing or resources?", "An authorized, reviewable decision should be recorded", ["The requester edits the outcome directly", "The change remains undocumented", "A public poll exposes all private details"], "Requests become civic action through bounded authority, reasons, and records.", "article-xiv-governance-framework", "Accountable administration"),
  concept("public-civic-practice", "09", "What does the public population ticker count?", "Active virtual symbolic citizens in the Citizen Register", ["Every site visitor", "Every quiz attempt", "All newsletter subscribers"], "Population derives from recorded civic standing rather than analytics traffic.", "immigration-codex", "Symbolic citizen register"),
  concept("public-civic-practice", "10", "What is the safest default for sensitive form data in a prototype?", "Keep it local or ephemeral and clearly state that it is not retained", ["Publish it to the ledger", "Store it indefinitely without notice", "Send it to unrelated services"], "Prototype interaction must not imply safeguards or persistence that do not yet exist.", "article-iii-rights-freedoms", "Privacy and informed participation"),
];

const variantLeadIns = [
  (prompt) => prompt,
  (prompt) => `Which answer best reflects the Corpus when asked: ${prompt}`,
  (prompt) => `During civic orientation, a Hopeful is asked: ${prompt}`,
  (prompt) => `Choose the response most consistent with Utopian civic practice: ${prompt}`,
];

export const assessmentQuestionBank = concepts.flatMap((base) => variantLeadIns.map((leadIn, variantIndex) => ({
  id: `${base.id}-v${variantIndex + 1}`,
  conceptId: base.id,
  category: base.category,
  prompt: leadIn(base.prompt),
  options: [base.correct, ...base.distractors],
  correctOption: 0,
  explanation: base.explanation,
  sourceSlug: base.sourceSlug,
  sourceSection: base.sourceSection,
  approved: true,
})));

export const easterEggQuestion = {
  id: "easter-unladen-swallow",
  conceptId: "easter-unladen-swallow",
  category: "easter-egg",
  prompt: "What is the air-speed velocity of an unladen swallow?",
  responseType: "text",
  recognizedResponse: "African or European?",
  scored: false,
};

export function questionsForCategory(categoryKey) {
  return assessmentQuestionBank.filter((question) => question.category === categoryKey && question.approved);
}

export function questionById(questionId) {
  return assessmentQuestionBank.find((question) => question.id === questionId) || null;
}

export function questionSourceHref(question) {
  if (question.sourceSlug === "circle-of-harmony-charter") return "/circles/harmony#corpus-authority";
  if (question.sourceSlug === "circle-of-balance-charter") return "/circles/balance#corpus-authority";
  return `/corpus/${question.sourceSlug}`;
}

export function bankSummary() {
  return assessmentCategories.map((category) => ({
    ...category,
    approvedQuestions: questionsForCategory(category.key).length,
    concepts: new Set(questionsForCategory(category.key).map((question) => question.conceptId)).size,
  }));
}
